library={"prefix":"lib/","thumbnail_ext":["jpg","png"],"track_ext":["mp3","ogg"],"lyrics_ext":["lyrics"],"movie_ext":["mp4","ogv","mkv","webm"],"lib":[
"Beethoven - Moonlight Sonata/Beethoven - Moonlight Sonata-1.mp3",
"Beethoven - Moonlight Sonata/Beethoven - Moonlight Sonata-2.mp3",
"Beethoven - Moonlight Sonata/Beethoven - Moonlight Sonata-3.mp3",
"Matrix/Chateau-KCNOe7s1lD0.jpg",
"Matrix/Chateau-KCNOe7s1lD0.ogg",
"Matrix/Clubbed to Death - Matrix-wAObbLeRIEQ.jpg",
"Matrix/Clubbed to Death - Matrix-wAObbLeRIEQ.ogg",
"Matrix/Furious Angels (Instrumental)-9GCjRXUICac.jpg",
"Matrix/Furious Angels (Instrumental)-9GCjRXUICac.ogg",
"Matrix/Mona Lisa Overdrive-PB9Mi_hf7og.jpg",
"Matrix/Mona Lisa Overdrive-PB9Mi_hf7og.ogg",
"Matrix/Navras-TXoSPAGUH2M.jpg",
"Matrix/Navras-TXoSPAGUH2M.lyrics",
"Matrix/Navras-TXoSPAGUH2M.ogg",
"Matrix/Rob Dougan/Born Yesterday (Instrumental)-Sae-OjAKotE.jpg",
"Matrix/Rob Dougan/Born Yesterday (Instrumental)-Sae-OjAKotE.ogg",
"Matrix/Rob Dougan/There's Only Me (Instrumental)-1aGwviwnDhQ.jpg",
"Matrix/Rob Dougan/There's Only Me (Instrumental)-1aGwviwnDhQ.ogg",
"thumbnail.png",
"videos/Code Editor Slander...-RHh888YSCoc.webm",
"videos/How MIT Decides Who to Reject in 30 Seconds-p5GQSf1gxbk.webm",
"videos/Programmer Slander 2-7GPSpmJbjV0.webm",
"videos/Programmer Slander-Tdbr_wm6rI4.webm",
"videos/Software Engineering slander-JOrpV9ONUE0.webm",
]}
